# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv='' --character-set-server=latin1 --collation-server=latin1_general_ci
    restart: always
    volumes:
    - ../data/test_db:/docker-entrypoint-initdb.d
    - ../request:/request
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080